# Generated by Django 4.1.1 on 2022-09-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAgencia', models.CharField(help_text='Ingrese el Nombre de la Persona de la agencia', max_length=100)),
                ('direccionAgencia', models.CharField(help_text='Ingrese la Direccion de la Persona de la agencia', max_length=100)),
                ('telefonoAgencia', models.CharField(help_text='Ingrese el Telefono de la Persona de la agencia', max_length=12)),
                ('ciudadAgencia', models.CharField(help_text='Ingrese la Ciudad de la persona de la agencia', max_length=100)),
            ],
            options={
                'verbose_name': 'agencia',
                'verbose_name_plural': 'agencias',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedulaPersona', models.CharField(help_text='Ingrese la Cedula', max_length=10)),
                ('nombrePersona', models.CharField(help_text='Ingrese el Nombre de la Persona', max_length=100)),
                ('apellidoPersona', models.CharField(help_text='Ingrese el Apellido de la Persona', max_length=100)),
                ('direccionPersona', models.CharField(help_text='Ingrese la Direccion de la Persona', max_length=100)),
                ('telefonoPersona', models.CharField(help_text='Ingrese el Telefono de la Persona', max_length=12)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedulaReserva', models.CharField(help_text='Ingrese la Cedula', max_length=10)),
                ('nitavReserva', models.CharField(help_text='Ingrese el Nit de la agencia de viaje', max_length=100)),
                ('fechaingresoReserva', models.CharField(help_text='Ingrese la fecha de ingreso', max_length=100)),
                ('fechasalidaReserva', models.CharField(help_text='Ingrese la fecha de salida', max_length=100)),
                ('horaingresoReserva', models.CharField(help_text='Ingrese la Hora de ingreso', max_length=12)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.agencia')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.hoteles')),
                ('personas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
