# Generated by Django 4.1.3 on 2022-11-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaingresoReserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fechasalidaReserva',
            field=models.DateField(),
        ),
    ]
