# Generated by Django 4.1.3 on 2022-11-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteles',
            old_name='añodeconstruccionHoteles',
            new_name='año',
        ),
    ]
